/*
* festradasolano
*/
package net.mashment.drools.rules

//list any import classes here.

import net.mashment.drools.entities.OFPort;

//declare any global variables here


rule "Test OFPort"

    when
        //conditions
        $p : OFPort(receivedPackets > 200)
    then
        //actions
        System.out.println("OFPort number " + $p.getNumber() + ", from switch " + $p.getSw().getDpid() + ", in NOS " + $p.getSw().getNos().getType() +  ", received more than 200 packets");

end
