/*
* festradasolano
*/
package net.mashment.drools.rules

//list any import classes here.

import net.mashment.drools.entities.Port;

//declare any global variables here


rule "Test Port"

    when
        //conditions
        $p : Port(receivePackets > 200)
    then
        //actions
        System.out.println("Port number " + $p.getNumber() + ", from switch " + $p.getSw().getDpid() + ", in NOS " + $p.getSw().getNos().getType() +  ", received more than 200 packets");

end
